doctrine_migrations:
    migrations_paths:
        'DatingLibre\AppBundle\Migrations': '@DatingLibreAppBundle/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
