monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: ["!event", "!doctrine"]
        doctrine:
            level: warning
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels: ["doctrine"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
