version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: memory

  s3ninja:
    restart: always
    image: scireum/s3-ninja:6.4
    ports:
      - "9444:9000"